### PR TITLE
Bump to 0.4.0

### PR DESCRIPTION
**Pull request by CleanCut**
@jlowry Want to test pulling this in as a branch before we release?

### CODE REVIEW

**Comment by CleanCut** [comment]
Gentle nudge.

**Comment by jlowry** [comment]
It's in use on legion_v2 and seems to be working.

**Review by jlowry — APPROVED** [review]
Looks good.

bors r+

**Comment by CleanCut** [comment]
@jlowry I gave you write permissions to this repo, which should enable bors to work for you in the future.

bors r+

**Comment by CleanCut** [comment]
`serde-diff` and `serde-diff-derive` `v0.4.0` have been released.

**Pull request merged**
